### ISSUE TITLE
Opening SheLi causes Error sometimes

### ISSUE THREAD

**Issue by bugy** [bugy/shop-list#103]
No known steps to reproduce. Sometimes (especially after long inactive time), when you open the app, it crashes immediately. On reopening it works fine. 
Supposely bug happens if application was opened (but minimized) and OperatingSystem decided to clear RAM. However I don't know how to trigger such clear in order to test it

A corresponding stacktrace:
```
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{net.buggy.shoplist/net.buggy.shoplist.ShopListActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2342)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
at android.app.ActivityThread.access$800(ActivityThread.java:154)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5290)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
at net.buggy.shoplist.units.Unit.addRenderer(Unit.java:64)
at net.buggy.shoplist.units.ShopItemListUnit.initialize(ShopItemListUnit.java:74)
at net.buggy.shoplist.units.Unit.start(Unit.java:49)
at net.buggy.shoplist.ShopListActivity.restartUnits(ShopListActivity.java:340)
at net.buggy.shoplist.ShopListActivity.onCreate(ShopListActivity.java:115)
at android.app.Activity.performCreate(Activity.java:6039)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
... 10 more
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.put(java.lang.Object, java.lang.Object)' on a null object reference
at net.buggy.shoplist.units.Unit.addRenderer(Unit.java:64)
at net.buggy.shoplist.units.ShopItemListUnit.initialize(ShopItemListUnit.java:74)
at net.buggy.shoplist.units.Unit.start(Unit.java:49)
at net.buggy.shoplist.ShopListActivity.restartUnits(ShopListActivity.java:340)
at net.buggy.shoplist.ShopListActivity.onCreate(ShopListActivity.java:115)
at android.app.Activity.performCreate(Activity.java:6039)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
at android.app.ActivityThread.access$800(ActivityThread.java:154)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5290)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

**Comment by bugy** [comment]
I fixed one problem, but the error can still happen in some other places (in code). I didn't find a way to reproduce the problem at all, so couldn't test my fix
